### ISSUE TITLE
Failling to run any rake task when capistrano-confirm is part of Gemfile

### ISSUE THREAD

**Issue by rafamanzo** [jinzhu/capistrano-confirm#1]
Hi,

After installing my app on a new computer i keep getting the following error:

```
rafael@BURN-E:~/workspace/media-choice$ bundle exec rake spec --trace
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/aws-sdk-1.3.6/lib/aws/core.rb:62: warning: already initialized constant VERSION
rake aborted!
wrong number of arguments (0 for 1)
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:243:in `load'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/capistrano-confirm-0.0.3/lib/capistrano/confirm.rb:5:in `<top (required)>'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/bundler-1.1.3/lib/bundler/runtime.rb:74:in `require'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/bundler-1.1.3/lib/bundler/runtime.rb:74:in `rescue in block in require'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/bundler-1.1.3/lib/bundler/runtime.rb:62:in `block in require'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `each'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `require'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@media-choice/gems/bundler-1.1.3/lib/bundler.rb:119:in `require'
/home/rafael/workspace/media-choice/config/application.rb:9:in `<top (required)>'
/home/rafael/workspace/media-choice/Rakefile:5:in `require'
/home/rafael/workspace/media-choice/Rakefile:5:in `<top (required)>'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `block in load_rakefile'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/bin/rake:19:in `load'
/home/rafael/.rvm/gems/ruby-1.9.3-p0@global/bin/rake:19:in `<main>'
```

If I comment capistrano-confirm from my Gemfile, everything works fine. I took a look on the code but I couldn't figure out what's the problem.

Here is my current installed gems also:

```
rafael@BURN-E:~/workspace/media-choice$ gem list

*** LOCAL GEMS ***

actionmailer (3.2.2)
actionpack (3.2.2)
activemodel (3.2.2)
activerecord (3.2.2)
activeresource (3.2.2)
activesupport (3.2.2)
acts-as-taggable-on (2.1.1)
addressable (2.2.7)
amazon-ec2 (0.9.17)
arel (3.0.2)
awesome_nested_set (2.1.2)
aws-s3 (0.6.2)
aws-sdk (1.3.6)
bbenezech-nested_form (0.0.5)
bcrypt-ruby (3.0.1)
bootstrap-sass (2.0.1)
builder (3.0.0)
bundler (1.1.3)
capistrano (2.9.0)
capistrano-confirm (0.0.3)
capistrano-ext (1.2.1)
carmen (0.2.12)
chronic (0.6.7)
cocaine (0.2.1)
coffee-rails (3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.2.0)
daemon_controller (1.0.0)
delayed_job (3.0.1)
delayed_job_active_record (0.3.2)
devise (2.0.4)
diff-lcs (1.1.3)
erubis (2.7.0)
escape (0.0.4)
exception_notification (2.5.2)
execjs (1.3.0)
factory_girl (2.6.1)
factory_girl_rails (1.7.0)
faraday (0.7.6)
fastthread (1.0.7)
foreman (0.40.0)
google-analytics-rails (0.0.1)
haml (3.1.4)
hashie (1.2.0)
highline (1.6.11)
hike (1.2.1)
hpricot (0.8.6)
httparty (0.8.1)
i18n (0.6.0)
journey (1.0.3)
jquery-rails (2.0.1)
json (1.6.5)
kaminari (0.13.0)
libv8 (3.3.10.4 x86_64-linux)
mail (2.4.3)
mediaelement_rails (0.2)
metaclass (0.0.1)
mime-types (1.17.2)
mocha (0.10.5)
multi_json (1.1.0)
multi_xml (0.4.1)
multipart-post (1.1.5)
mysql2 (0.3.11)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.3.0)
net-ssh-gateway (1.1.0)
nokogiri (1.5.0)
oauth2 (0.5.2)
omniauth (1.0.3)
omniauth-facebook (1.2.0)
omniauth-oauth2 (1.0.0)
orm_adapter (0.0.6)
paperclip (2.7.0)
passenger (3.0.11)
polyglot (0.3.3)
pr_geohash (1.0.0)
rack (1.4.1)
rack-cache (1.2)
rack-pjax (0.5.8)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.2)
railties (3.2.2)
rake (0.9.2.2)
rdoc (3.12)
recaptcha (0.3.4)
RedCloth (4.2.9)
remotipart (1.0.2)
right_aws (3.0.0)
right_http_connection (1.3.0)
rsolr (1.0.7)
rspec (2.8.0)
rspec-core (2.8.0)
rspec-expectations (2.8.0)
rspec-mocks (2.8.0)
rspec-rails (2.8.1)
rubygems-bundler (0.9.0)
rvm (1.11.3.3)
sanitize (2.0.3)
sass (3.1.15)
sass-rails (3.2.4)
sequel (3.33.0)
shoulda-matchers (1.0.0)
simplecov (0.6.1)
simplecov-html (0.5.3)
sprockets (2.1.2)
sqlite3 (1.3.5)
state_machine (1.1.2)
sunspot (1.3.0)
sunspot_rails (1.3.0)
sunspot_solr (1.3.0)
term-ansicolor (1.0.7)
therubyracer (0.9.10)
thor (0.14.6)
tilt (1.3.3)
treetop (1.4.10)
trollop (1.16.2)
tzinfo (0.3.32)
uglifier (1.2.3)
useragent (0.4.6)
uuidtools (2.1.2)
warden (1.1.1)
whenever (0.7.3)
will_paginate (3.0.3)
xml-simple (1.1.1)
zencoder (2.3.3)
zencoder-fetcher (0.2.7)
```

Do you have any thoughts?

Thank you very much!

**Comment by jinzhu** [comment]
Hi

Have you tried with the latest release v0.0.4 (released today) and latest capistrano (2.12.0)?

Seems it works well for me. could you confirm this? Thanks.
